#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx restart'
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
